// Generated by CoffeeScript 1.7.1
var $, FPS;

$ = jQuery;

FPS = 100;

window.canvas = document.getElementById('game');

window.rect = window.canvas.getBoundingClientRect();

window.canvas.width = window.canvas.height = 550;

window.ctx = window.canvas.getContext('2d');

window.GAME_START = false;

window.ROUND_START = false;

window.LIVES = 3;

window.LEVEL = 1;

document.getElementById('lifecount').innerHTML = window.LIVES;

document.getElementById('levelcount').innerHTML = window.LEVEL;

document.getElementById('message').innerHTML = "Click to play!";

$('#game').click(function(e) {});

$('#gamebox').mousemove(function(e) {});

update()(function() {});

draw(function() {
  window.ctx.clearRect(0, 0, 550, 550);
});

gameLoop()(function() {
  update();
  draw();
});

setInterval(gameLoop, 1000 / FPS);
